import csv
import datetime
import re
from pathlib import Path
from collections import defaultdict

def read_csv(filepath):
    if not Path(filepath).exists():
        return []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        return list(reader)

def generate_markdown_table(data, headers, keys):
    if not data:
        return "*No data available.*\n"

    header_row = "| " + " | ".join(headers) + " |"
    separator_row = "| " + " | ".join(["---"] * len(headers)) + " |"

    rows = []
    for item in data:
        row = []
        for key in keys:
            val = item.get(key, "")
            val = str(val).replace('\n', ' ').replace('\r', '')
            row.append(val)
        rows.append("| " + " | ".join(row) + " |")

    return "\n".join([header_row, separator_row] + rows) + "\n"

def main():
    tracker_file = Path('tracker/work_tracker.csv')
    coverage_file = Path('tracker/source_coverage.csv')
    daily_log_file = Path('tracker/daily_log.csv')
    today_md_file = Path('dashboard/today.md')
    readme_file = Path('README.md')
    dashboard_readme_file = Path('dashboard/README.md')

    tasks = read_csv(tracker_file)
    coverage = read_csv(coverage_file)
    logs = read_csv(daily_log_file)

    # Calculate metrics
    total_tasks = len(tasks)
    status_counts = defaultdict(int)

    for t in tasks:
        status_counts[t.get('Status', 'Unknown')] += 1

    done = status_counts.get('Done', 0)
    in_progress = status_counts.get('In Progress', 0)
    not_started = status_counts.get('Not Started', 0)
    blocked_count = status_counts.get('Blocked', 0)
    parked = status_counts.get('Parked', 0)

    completion_percentage = (done / total_tasks * 100) if total_tasks > 0 else 0

    # Summary metrics table
    summary_metrics_table = f"| Total | Done | In Progress | Not Started | Blocked | Parked | Completion |\n|---:|---:|---:|---:|---:|---:|---:|\n| {total_tasks} | {done} | {in_progress} | {not_started} | {blocked_count} | {parked} | {completion_percentage:.1f}% |\n"

    # Partial source coverage items
    partial_coverage = [c for c in coverage if c.get('Coverage') in ['Partial', 'None']]

    # Sort logs by date desc to get recent
    logs.sort(key=lambda x: x.get('Date', ''), reverse=True)
    recent_logs = logs[:10]

    # Read today.md content
    today_content = "*`dashboard/today.md` is missing. Please run `python scripts/rank_tasks.py` to generate the daily action plan.*"
    if today_md_file.exists():
        with open(today_md_file, 'r', encoding='utf-8') as f:
            today_content = f.read()

    # Generate dashboard content
    now_utc = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')

    md = [
        "<!-- GENERATED CONTENT START: Do not manually edit this block. Generated by scripts/build_dashboard.py -->",
        f"*Last generated: {now_utc}*\n",
        "## Summary Metrics\n",
        summary_metrics_table,
        today_content,
        "## Partial/Uncovered Source Items\n",
        generate_markdown_table(
            partial_coverage,
            ["Source", "Request / Wishlist Item", "Covered in tracker task(s)", "Coverage"],
            ["Source", "Request / Wishlist Item", "Covered in tracker task(s)", "Coverage"]
        ),
        "## Full Tracker\n",
        generate_markdown_table(
            tasks,
            ["TaskID", "Category", "Task", "Status", "Priority", "ReadyStatus", "DependsOn", "Effort", "NextAction", "BlockedBy"],
            ["TaskID", "Category", "Task", "Status", "Priority", "ReadyStatus", "DependsOn", "Effort", "NextAction", "BlockedBy"]
        ),
        "<!-- GENERATED CONTENT END -->"
    ]

    dashboard_content = "\n".join(md)

    # Overwrite dashboard block in root README.md
    if readme_file.exists():
        with open(readme_file, 'r', encoding='utf-8') as f:
            readme_text = f.read()

        start_marker = "<!-- DASHBOARD:START -->"
        end_marker = "<!-- DASHBOARD:END -->"

        pattern = re.compile(rf"{re.escape(start_marker)}.*?{re.escape(end_marker)}", re.DOTALL)
        if pattern.search(readme_text):
            new_readme_text = pattern.sub(f"{start_marker}\n{dashboard_content}\n{end_marker}", readme_text)
            with open(readme_file, 'w', encoding='utf-8') as f:
                f.write(new_readme_text)
        else:
            print(f"Warning: DASHBOARD markers not found in {readme_file}. Root README not updated.")

    # Also keep generating dashboard/README.md for backward compatibility
    Path('dashboard').mkdir(parents=True, exist_ok=True)
    with open(dashboard_readme_file, 'w', encoding='utf-8') as f:
        f.write("# X-Boundaries Automation Dashboard\n\n" + dashboard_content)

if __name__ == '__main__':
    main()
